frequency: 20.0
model_state_frequency: 10.0
self_manage: true
leg_support_distance: 0.2
joint_states: joint_states
odometry: /odom_raw
joint_controller: position_trajectory_controller
effort_controller: /effort_controller/commands
chain0: "[leg] base_link => r_sole"
chain1: "[leg] base_link => l_sole"

